# Generated by Django 5.2 on 2025-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("flat", "Flat"), ("percent", "Percentage")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
