# Generated by Django 5.2 on 2025-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_discount_type_product_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_printed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Discount Type"),
                    ("flat", "Flat"),
                    ("percent", "Percentage"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
