# Generated by Django 5.2 on 2025-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("store", "0003_product_is_printed_alter_product_discount_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="customers",
            field=models.ManyToManyField(blank=True, to="accounts.customer"),
        ),
    ]
