# Generated by Django 5.2 on 2025-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_discount_customers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceitem",
            old_name="price_at_purchase",
            new_name="discount_at_purchase",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="product_discount",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="product",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="product_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
