# Generated by Django 5.2 on 2025-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "store",
            "0005_rename_price_at_purchase_invoiceitem_discount_at_purchase_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
