# Generated by Django 5.2.1 on 2025-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_invoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10),
        ),
    ]
