# Generated by Django 5.2.1 on 2025-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
