# Generated by Django 5.2 on 2025-05-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
