# Generated by Django 5.2.1 on 2025-06-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
        ('store', '0011_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='bill_image',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand'),
        ),
    ]
