# Generated by Django 5.2.1 on 2025-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_width', models.FloatField(blank=True, null=True, verbose_name='Total Width (mm)')),
                ('total_height', models.FloatField(blank=True, null=True, verbose_name='Total Height (mm)')),
                ('labels_across', models.IntegerField(default=1, verbose_name='Labels Across')),
                ('label_width', models.FloatField(verbose_name='Label Width (mm)')),
                ('label_height', models.FloatField(verbose_name='Label Height (mm)')),
                ('gap_left', models.FloatField(default=0, verbose_name='Left Gap (mm)')),
                ('gap_right', models.FloatField(default=0, verbose_name='Right Gap (mm)')),
                ('gap_top', models.FloatField(default=0, verbose_name='Top Gap (mm)')),
                ('gap_bottom', models.FloatField(default=0, verbose_name='Bottom Gap (mm)')),
                ('round_top_left', models.FloatField(default=0, verbose_name='Top-Left Corner Radius (mm)')),
                ('round_top_right', models.FloatField(default=0, verbose_name='Top-Right Corner Radius (mm)')),
                ('round_bottom_left', models.FloatField(default=0, verbose_name='Bottom-Left Corner Radius (mm)')),
                ('round_bottom_right', models.FloatField(default=0, verbose_name='Bottom-Right Corner Radius (mm)')),
            ],
        ),
    ]
