# Generated by Django 5.2.1 on 2025-05-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
