# Generated by Django 5.2.1 on 2025-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_labeltemplate_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='gap_bottom',
            field=models.FloatField(blank=True, null=True, verbose_name='Bottom Gap (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='gap_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Left Gap (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='gap_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Right Gap (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='gap_top',
            field=models.FloatField(blank=True, null=True, verbose_name='Top Gap (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Label Height (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Label Width (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='labels_across',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Labels Across'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='round_bottom_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Bottom-Left Corner Radius (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='round_bottom_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Bottom-Right Corner Radius (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='round_top_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Top-Left Corner Radius (mm)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='round_top_right',
            field=models.FloatField(blank=True, null=True, verbose_name='Top-Right Corner Radius (mm)'),
        ),
    ]
