# Generated by Django 5.2.1 on 2025-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_labeltemplate_is_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='is_billing_default',
            field=models.BooleanField(default=False),
        ),
    ]
